### ISSUE TITLE
UI is a bit bulky

### ISSUE THREAD

**Issue by hubbardp** [JaneliaSciComp/neuronbridge-vol-viewer#3]
The controls at the top of the UI ("Toggle", "EM Color", "Mirror", "LM Color", etc.) are fairly "bulky", in that the window has to be pretty wide to avoid having the controls get wrapped onto a second line in a rather unglamorous looking way.   And the width necessary to avoid wrapping also changes: pressing the "Mirror" button changes its text to "Unmirror", which can cause wrapping that had not been present before.

Would it be possible to make the controls slimmer, and maybe also make it so their spacing will adjust dynamically to avoid wrapping?

One reason this issue is important is that the size of the rendered image matches the size of the window, and a larger rendered image takes longer to render.  So users with less-capable systems may want to make the window smaller to get more interactivity.

**Comment by neomorphic** [comment]
I don't want to place the controls too much closer or make them too much smaller. This is an accessibility issue and small close together controls are not great, especially on a small screen or touch enabled device. I plan on moving the toggle / mirror and color controls onto a line with their respective LM /EM labels, so that should free up some of the width. There are also better ways to layout the controls, so that they are aligned in a sensible manner when the window size is smaller. There is also the option that they will get hidden in a menu by when making the window smaller.

**Comment by neomorphic** [comment]
Controls have been moved into a sidebar that can be collapsed.
